### ISSUE TITLE
Would it be possible to add custom examine text?

### ISSUE THREAD

**Issue by Ferrariic** [Jarvinnn/meepspeak#1]

**Comment by jarvin-s** [comment]
I'm sure it's possible but as of currently I have no plans to, sorry. I had quite a lot of help with the plugin and not really looking to ask the person again, I'll definitely keep it in mind for the future though.

The focus of this plugin was to only change NPC/Item names and not being able to change them yourself. That feature just so happened to be added along the way, but because of that, your idea is not a bad idea for the future.

**Comment by Ferrariic** [comment]
Thanks :)
